services:
  db:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=cancellation
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nestjs-api
  #   environment:
  #     - DATABASE_URL=postgres://user:password@db:5432/cancellation
  #     - RABBITMQ_URL=amqp://rabbitmq:5672
  #     - RABBITMQ_QUEUE=cancellation
  #     - TEST_DATABASE_URL=postgres://user:password@db:5432/test_db
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - rabbitmq
  #     - db
  #   volumes:
  #     - ./src:/app/src

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  pgdata:
    driver: local
